/** Server-side playtest analytics event types — gameplay behaviour only. */
export const GAMEPLAY_ANALYTICS_EVENTS = {
  ROUND_ACTIVATED: 'ROUND_ACTIVATED',
  PLAYER_SESSION_STARTED: 'PLAYER_SESSION_STARTED',
  SCOUT_COMPLETED: 'SCOUT_COMPLETED',
  PRODUCE_COMPLETED: 'PRODUCE_COMPLETED',
  SHOP_PURCHASED: 'SHOP_PURCHASED',
  SHOP_CART_PURCHASED: 'SHOP_CART_PURCHASED',
  SHOP_SOLD: 'SHOP_SOLD',
  ATTACK_COMPLETED: 'ATTACK_COMPLETED',
  PLAYER_INTEL_SCOUTED: 'PLAYER_INTEL_SCOUTED',
  TRAVEL_COMPLETED: 'TRAVEL_COMPLETED',
  MARKET_LISTED: 'MARKET_LISTED',
  MARKET_BID: 'MARKET_BID',
  MARKET_PURCHASED: 'MARKET_PURCHASED',
  BUSINESS_PURCHASED: 'BUSINESS_PURCHASED',
  BUSINESS_UPGRADED: 'BUSINESS_UPGRADED',
  BUSINESS_WORKERS_ASSIGNED: 'BUSINESS_WORKERS_ASSIGNED',
  BUSINESS_WORKERS_REMOVED: 'BUSINESS_WORKERS_REMOVED',
  CARTEL_CREATED: 'CARTEL_CREATED',
  CARTEL_JOINED: 'CARTEL_JOINED',
  CARTEL_LEFT: 'CARTEL_LEFT',
  TURN_GRANT_RECEIVED: 'TURN_GRANT_RECEIVED',
  HIRE_THUGS: 'HIRE_THUGS',
} as const;

export type GameplayAnalyticsEventType =
  (typeof GAMEPLAY_ANALYTICS_EVENTS)[keyof typeof GAMEPLAY_ANALYTICS_EVENTS];

/** Minimum inactivity gap before a new session is counted (30 minutes). */
export const SESSION_GAP_MS = 30 * 60 * 1000;
