/** Gameplay action pending copy — shown while server actions resolve. */
export const ACTION_PENDING = {
  scout: 'Scouting…',
  produce: 'Producing…',
  attack: 'Attacking…',
  intel: 'Gathering intel…',
  deepIntel: 'Gathering deep intel…',
  shopPurchase: 'Buying…',
  shopSell: 'Selling…',
  hireThugs: 'Hiring…',
  releaseThugs: 'Releasing…',
  marketBid: 'Placing bid…',
  marketList: 'Listing…',
  cartelInvite: 'Sending…',
  cartelJoin: 'Sending…',
  cartelCreate: 'Creating…',
  cartelArmoury: 'Purchasing…',
  cartelAction: 'Working…',
  businessPurchase: 'Purchasing…',
  businessUpgrade: 'Upgrading…',
  businessCollect: 'Collecting cash…',
  businessAction: 'Updating…',
  payout: 'Saving…',
  travel: (destination: string) => `Travelling to ${destination}…`,
} as const;
