-- Empire Phase 2: activity types for payout, bank, empire

ALTER TYPE "ActivityCategory" ADD VALUE IF NOT EXISTS 'WORKER_PAYOUT_UPDATED';
ALTER TYPE "ActivityCategory" ADD VALUE IF NOT EXISTS 'BANK_DEPOSIT';
ALTER TYPE "ActivityCategory" ADD VALUE IF NOT EXISTS 'BANK_WITHDRAWAL';
ALTER TYPE "ActivityCategory" ADD VALUE IF NOT EXISTS 'PERSONNEL_DISMISSED';
ALTER TYPE "ActivityCategory" ADD VALUE IF NOT EXISTS 'EMPIRE_UPDATED';
