import {
  Home,
  Crown,
  Crosshair,
  Factory,
  ShoppingCart,
  Trophy,
  User,
  Eye,
  Target,
  FileText,
  BookOpen,
  Gavel,
  Map,
  Users,
  Heart,
  Shield,
  Package,
  Smile,
  Coins,
  Clock,
  Wallet,
  TrendingUp,
  TriangleAlert,
  CircleCheck,
  CircleX,
  MoreHorizontal,
  Car,
  Search,
  type LucideIcon,
} from 'lucide-react';

/** Tree-shakeable icon map — one import site for the whole game */
export const GAME_ICONS = {
  home: Home,
  empire: Crown,
  scout: Crosshair,
  produce: Factory,
  shop: ShoppingCart,
  rankings: Trophy,
  player: User,
  intel: Eye,
  attack: Target,
  reports: FileText,
  guides: BookOpen,
  market: Gavel,
  travel: Map,
  cartel: Users,
  more: MoreHorizontal,
  health: Heart,
  workers: Users,
  thugs: Shield,
  weapons: Crosshair,
  vehicles: Car,
  drugs: Package,
  supplies: Package,
  happiness: Smile,
  payout: Coins,
  turns: Clock,
  cash: Wallet,
  netWorth: TrendingUp,
  rank: Trophy,
  warning: TriangleAlert,
  success: CircleCheck,
  failure: CircleX,
  search: Search,
} as const satisfies Record<string, LucideIcon>;

export type GameIconName = keyof typeof GAME_ICONS;

/** Icons for primary action buttons keyed by route/action */
export const GAME_ACTION_ICONS = {
  scout: 'scout',
  produce: 'produce',
  shop: 'shop',
  rankings: 'rankings',
  attack: 'attack',
  buy: 'shop',
  save: 'payout',
  reports: 'reports',
  cancel: 'failure',
} as const satisfies Record<string, GameIconName>;
